server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /www/bpirouter;
    index index.html;

    include /etc/nginx/conf.d/bpirouter-locations.inc;
}
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    root /www/bpirouter;
    index index.html;

    ssl_certificate     /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    include /etc/nginx/conf.d/bpirouter-locations.inc;
}
